project:
  name: "Разработка веб-приложения"
  deadline: "2024-12-31"
  team:
    Разработчик:
      Иван Иванов:
        experience: 12
      Анна Петрова:
        experience: 3
    Дизайнер:
      Светлана Сидорова:
        experience: 4
  tasks:
    Создание макета:
      assigned_to: "Светлана Сидорова"
      status: "В процессе"
    Разработка бэкенда:
      assigned_to: "Иван Иванов"
      status: "Не начато"
    Тестирование:
      assigned_to: "Анна Петрова"
      status: "Не начато"